name: Bug 报告
description: 提交一个 bug
labels: bug

body:
  - type: markdown
    attributes:
      value: |
        感谢您来到这里

        在反馈前, 请确认您已经做了下面这些事情
        - 阅读过 [「提问的智慧」](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
        - 阅读过 [「如何有效地报告 Bug」](https://www.chiark.greenend.org.uk/~sgtatham/bugs-cn.html)
        - 对照过 [Releases](https://github.com/wssy001/fallout76-public/releases)，相关问题未在近期更新中解决
        - 搜索了已有的 [issues - bug](https://github.com/wssy001/fallout76-public/labels/bug) 列表中有没相关的信息

  - type: textarea
    id: issue-description
    attributes:
      label: 问题描述
      description: 在此详细描述您遇到的问题
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 复现
      description: 在这里简略说明如何让这个问题再次发生
      placeholder: |
        在这里简略说明如何让这个问题再次发生
        可使用 1.  2.  3.  的列表格式，或其他任意恰当的格式
        如果您不确定如何复现, 请尽量描述发生当时的情景
        建议提供相关代码
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 辐射76小助手 版本
      description: "填写您正在使用的版本号，如 `0.1.0.dev`"
      placeholder: 0.1.0.dev
    validations:
      required: true

  - type: dropdown
    id: runtime-platform
    attributes:
      label: 运行环境
      options:
        - Docker
        - Linux
        - Windows
        - Windows Server
        - MACOS
    validations:
      required: true

#  - type: textarea
#    id: journal-system
#    attributes:
#      label: 系统日志
#      description: |
#        请提供全面的相关日志. 请不要截图.
#        如果日志过大, 可以在 `补充信息` 上传文件.
#        如果您遇到的问题是 "消息收不到", "收消息报错" 等与协议有关的问题, 请一定提交日志. 若不提交日志, 您的问题可能会被直接关闭.
#      render: 'text'
#    validations:
#      required: false

  - type: textarea
    id: additional
    attributes:
      label: 其他信息
      description: "填填写具体的运行环境信息以及其他您觉得必须说明的内容，如 `Docker CE 20.10.12 自行使用Dockerfile构建 fallout76 0.3.0.dev JAR包版本`"
      placeholder: Docker CE 20.10.12 自行使用Dockerfile构建 fallout76 0.3.0.dev JAR包版本
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ----

        在发出 issue 前, 请确认

        - 全部信息已经填写完毕
        - 报告中没有令人反感的语言
        - 「复现」的描述是否足够详细准确
